# Generated by Django 3.1.7 on 2021-03-22 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=250)),
                ('commodity', models.CharField(max_length=250)),
                ('seed_type', models.CharField(max_length=250)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('supply_create', models.DateTimeField(auto_now_add=True)),
                ('supply_edit', models.DateTimeField(auto_now=True)),
                ('supply_date', models.DateTimeField()),
                ('zip_code', models.CharField(help_text='Enter google postal code', max_length=25)),
                ('city', models.CharField(max_length=250)),
                ('country', models.CharField(default='Nepal', editable=False, max_length=250)),
                ('province', models.CharField(max_length=250)),
                ('district', models.CharField(max_length=250)),
                ('municipal', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=250)),
                ('commodity', models.CharField(max_length=250)),
                ('seed_type', models.CharField(max_length=250)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('supply_create', models.DateTimeField(auto_now_add=True)),
                ('supply_edit', models.DateTimeField(auto_now=True)),
                ('supply_date', models.DateTimeField()),
                ('zip_code', models.CharField(help_text='Enter google postal code', max_length=25)),
                ('city', models.CharField(max_length=250)),
                ('country', models.CharField(default='Nepal', editable=False, max_length=250)),
                ('province', models.CharField(max_length=250)),
                ('district', models.CharField(max_length=250)),
                ('municipal', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
