# Generated by Django 3.1.7 on 2021-03-22 14:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bidding', '0002_auto_20210322_2030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Demand',
            new_name='Buyer',
        ),
        migrations.RenameModel(
            old_name='Supply',
            new_name='Supplier',
        ),
    ]
