# Generated by Django 3.1.7 on 2021-03-22 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bidding', '0005_demand_supply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demandside',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=250)),
                ('commodity', models.CharField(max_length=250)),
                ('seed_type', models.CharField(max_length=250)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('supply_create', models.DateTimeField(auto_now_add=True)),
                ('supply_edit', models.DateTimeField(auto_now=True)),
                ('supply_date', models.DateTimeField()),
                ('zip_code', models.CharField(help_text='Enter google postal code', max_length=25)),
                ('city', models.CharField(max_length=250)),
                ('country', models.CharField(default='Nepal', editable=False, max_length=250)),
                ('province', models.CharField(max_length=250)),
                ('district', models.CharField(max_length=250)),
                ('municipal', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supplyside',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=250)),
                ('commodity', models.CharField(max_length=250)),
                ('seed_type', models.CharField(max_length=250)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('supply_create', models.DateTimeField(auto_now_add=True)),
                ('supply_edit', models.DateTimeField(auto_now=True)),
                ('supply_date', models.DateTimeField()),
                ('zip_code', models.CharField(help_text='Enter google postal code', max_length=25)),
                ('city', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=False)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bidding.country')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bidding.district')),
                ('municipality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bidding.municipality')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bidding.province')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='supply',
            name='country',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='district',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='province',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='user',
        ),
        migrations.DeleteModel(
            name='Demand',
        ),
        migrations.DeleteModel(
            name='Supply',
        ),
    ]
