# Generated by Django 3.1.7 on 2021-03-22 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0008_auto_20210322_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandside',
            name='municipal',
        ),
        migrations.AddField(
            model_name='demandside',
            name='municipality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bidding.municipality'),
        ),
        migrations.AlterField(
            model_name='demandside',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bidding.country'),
        ),
        migrations.AlterField(
            model_name='demandside',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bidding.district'),
        ),
        migrations.AlterField(
            model_name='demandside',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bidding.province'),
        ),
    ]
