# Generated by Django 3.1.7 on 2021-03-22 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0009_auto_20210322_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidding.category')),
            ],
        ),
        migrations.CreateModel(
            name='SeedType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidding.category')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidding.commodity')),
            ],
        ),
        migrations.AlterField(
            model_name='demandside',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bidding.category'),
        ),
        migrations.AlterField(
            model_name='demandside',
            name='commodity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bidding.commodity'),
        ),
        migrations.AlterField(
            model_name='demandside',
            name='seed_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bidding.seedtype'),
        ),
        migrations.AlterField(
            model_name='supplyside',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bidding.category'),
        ),
        migrations.AlterField(
            model_name='supplyside',
            name='commodity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bidding.commodity'),
        ),
        migrations.AlterField(
            model_name='supplyside',
            name='seed_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bidding.seedtype'),
        ),
    ]
