# Generated by Django 3.1.7 on 2021-03-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0010_auto_20210322_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyside',
            name='slug',
            field=models.CharField(default='maize', max_length=250),
        ),
    ]
