# Generated by Django 3.1.7 on 2021-03-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0012_demandside_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_id', models.IntegerField()),
                ('demand_id', models.IntegerField()),
                ('txn_code', models.CharField(max_length=100)),
            ],
        ),
    ]
