# Generated by Django 3.1.7 on 2021-03-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0013_bidmatch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandside',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='supplyside',
            old_name='is_active',
            new_name='active',
        ),
        migrations.AddField(
            model_name='bidmatch',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bidmatch',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bidmatch',
            name='commodity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bidmatch',
            name='price',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='bidmatch',
            name='quantity',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
