# Generated by Django 3.1.7 on 2021-03-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0016_remove_bidmatch_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidmatch',
            name='seed_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
